# Generated by Django 3.2.25 on 2024-04-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_type',
            name='day',
            field=models.CharField(max_length=9),
        ),
    ]
