# Generated by Django 3.2.25 on 2024-04-09 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_class_day'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class_Day',
        ),
    ]
