# Generated by Django 3.2.25 on 2024-04-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_delete_class_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_type',
            name='day_number',
            field=models.IntegerField(default=1),
        ),
    ]
