# Generated by Django 3.2.25 on 2024-06-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0010_alter_ratings_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_type',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
