# Generated by Django 3.2.25 on 2024-06-15 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0011_alter_class_type_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class_type',
            name='rating',
        ),
    ]
