# Generated by Django 3.2.25 on 2024-06-09 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactdetails',
            old_name='full_name',
            new_name='user',
        ),
    ]
