# Generated by Django 3.2.25 on 2024-04-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationlineitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
