# Generated by Django 3.2.25 on 2024-04-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_reservationlineitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='original_basket',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='reservation',
            name='stripe_pid',
            field=models.CharField(default='', max_length=254),
        ),
    ]
